name = "PhyloSummaries"
uuid = "431a9082-0c03-4c0b-a224-e592b0e14882"
authors = ["Cecile Ane <cecileane@users.noreply.github.com>", "Joshua Justison <jjustison@users.noreply.github.com>", "and contributors"]
version = "0.1.0"

[deps]
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"

[compat]
PhyloNetworks = "1"
julia = "1.2"
