name = "PhyloSummaries"
uuid = "431a9082-0c03-4c0b-a224-e592b0e14882"
authors = ["Cecile Ane <cecileane@users.noreply.github.com>", "Joshua Justison <jjustison@users.noreply.github.com>", "and contributors"]
version = "0.1.0"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"

[compat]
Dictionaries = "0.4.5"
PhyloNetworks = "1.3"
julia = "1.2"
