[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4" # for jldoctests
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
PhyloPlots = "c0d5b6db-e3fc-52bc-a87d-1d050989ed3b"
PhyloSummaries = "431a9082-0c03-4c0b-a224-e592b0e14882"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[compat]
Documenter = "1"
PhyloNetworks = "1.3"
